### ISSUE TITLE
How to handle the missing libproc.h and other header files in iPhoneOS.sdk

### ISSUE THREAD

**Issue by wangkuiyi** [light-tech/LLVM-On-iOS#1]
Thank you for making something so great!

I had trouble building TensorFlow's XLA, which depends on LLVM, because the iPhoneOS SDK does not include libproc.h. For example

```
external/llvm-project/llvm/lib/Support/Timer.cpp:36:10: fatal error: 'libproc.h' file not found
#include <libproc.h>
```

I don't see any special code in the `build_llvm` Shell function for handling the 'HAVE_PROC_PID_RUSAGE' conditional macro.

Did you have to deal with the missing header files for iPhoneOS?

**Comment by light-tech** [comment]
I am building using GitHub Action and the [latest release build LLVM 15.0.3](https://github.com/light-tech/LLVM-On-iOS/releases/tag/llvm15.0.3) is using

 * Xcode 13.2.1
 * iPhoneOS15.2 SDK

My suspicion is that Apple might have removed the header `libproc.h` in the iOS SDK 16.x. I cannot check that for now since I cannot upgrade Xcode for now. Could you check your system configuration?

**Comment by wangkuiyi** [comment]
I see! Thank you for your prompt reply. I am using

- Xcode Version 14.1 (14B47b)
- Apple M1 Max
- macOS 13.0.1 (22A400)
-  iPhoneOS16.1.sdk

**Comment by light-tech** [comment]
> I see! Thank you for your prompt reply. I am using
> 
>     * Xcode Version 14.1 (14B47b)
> 
>     * Apple M1 Max
> 
>     * macOS 13.0.1 (22A400)
> 
>     * iPhoneOS16.1.sdk

You are welcome.

Just a quick update: Github Action now provides macos-12 host which has Xcode 14.0.1 and iOS 16.0 SDK installed so I fixed it a bit (to build `libffi`) and the latest LLVM 15.0.6 was [built successfully](https://github.com/light-tech/LLVM-On-iOS/releases/tag/llvm15.0.6) without any `libproc.h` issue.

**Comment by wangkuiyi** [comment]
My problem was that I build LLVM with Bazel, but iOS only works with LLVM's CMake rules, not Bazel rules.

Taking the including of `libproc.h` as an example.  The [including](https://github.com/llvm/llvm-project/blob/eb7c515d664c0ae6c17ad4094343b29cbd33719a/llvm/lib/Support/Timer.cpp#L35-L37) is protected by a macro `HAVE_PROC_PID_RUSAGE`.
```
#ifdef HAVE_PROC_PID_RUSAGE
#include <libproc.h>
#endif
```

The [CMake rules](https://github.com/llvm/llvm-project/blob/eb7c515d664c0ae6c17ad4094343b29cbd33719a/llvm/cmake/config-ix.cmake#L402) defines the value of the macro by checking the existence of `libproc.h`.
```
check_symbol_exists(proc_pid_rusage "libproc.h" HAVE_PROC_PID_RUSAGE)
```

However, [Bazel rules](https://github.com/llvm/llvm-project/blob/eb7c515d664c0ae6c17ad4094343b29cbd33719a/utils/bazel/llvm-project-overlay/llvm/config.bzl#L53) simply set the value to `1`.
```
    "HAVE_PROC_PID_RUSAGE=1",
```

The solution is to improve the Bazel rules of LLVM to support iOS.
