### ISSUE TITLE
Choose iPhoneOS SDK?

### ISSUE THREAD

**Issue by wangkuiyi** [light-tech/LLVM-On-iOS#3]
I have a question about the file `build-llvm.sh`.

When building for the iOS simulator, [it](https://github.com/light-tech/LLVM-On-iOS/blob/83ade6ce354b0c273a5502f6a31204b07d696f29/build-llvm.sh#L183) sets the CMake option [CMAKE_OSX_SYSROOT](https://cmake.org/cmake/help/latest/variable/CMAKE_OSX_SYSROOT.html) as
```
llvmCmakeArgs+=(-DCMAKE_OSX_SYSROOT=$(xcodebuild -version -sdk iphonesimulator Path));;
```

Why doesn't it set the above option to choose the SDK when building for iPhones, like this?

```
llvmCmakeArgs+=(-DCMAKE_OSX_SYSROOT=$(xcodebuild -version -sdk iphoneos Path));;
```

**Comment by wangkuiyi** [comment]
Oh. I got it -- the default value of `CMAKE_OSX_SYSROOT` is to build for the device, according to https://cmake.org/cmake/help/latest/manual/cmake-toolchains.7.html#cross-compiling-for-ios-tvos-or-watchos

**Comment by light-tech** [comment]
I think I simply followed some other tutorials.

Note that I did not set `CMAKE_SYSTEM_NAME=iOS` and the article you mentioned was using Xcode (`-GXcode`) generator for CMake (in which case, you also do not need to set `CMAKE_OSX_SYSROOT` and can instead add `-sdk iphonesimulator` when running `cmake --build`) while LLVM recommends Ninja.

**Comment by wangkuiyi** [comment]
I tried all three generators, Xcode, Ninja, and make, they all work with `CMAKE_SYSTEM_NAME=iOS`.

However, `cmake --build . -- -sdk iphonesimulator` does not work for me.
